sudo sh -c 'echo "4" > /sys/class/gpio/export'
sudo sh -c 'echo "out" > /sys/class/gpio/gpio4/direction'
sudo sh -c 'echo "1" > /sys/class/gpio/gpio4/value'
sudo sh -c 'echo "18" > /sys/class/gpio/export'
sudo sh -c 'echo "out" > /sys/class/gpio/gpio18/direction'
sudo sh -c 'echo "1" > /sys/class/gpio/gpio18/value'
sudo sh -c 'echo "6" > /sys/class/gpio/export'
sudo sh -c 'echo "out" > /sys/class/gpio/gpio6/direction'
sudo sh -c 'echo "1" > /sys/class/gpio/gpio6/value'
sudo sh -c 'echo "13" > /sys/class/gpio/export'
sudo sh -c 'echo "out" > /sys/class/gpio/gpio13/direction'
sudo sh -c 'echo "1" > /sys/class/gpio/gpio13/value'
sudo sh -c 'echo "20 21 3000" > /sys/class/distance-sensor/configure'
sudo sh -c 'echo "16 19 3000" > /sys/class/distance-sensor/configure'

