/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_restental_andreas_joystick_rumble_RumbleControl */

#ifndef _Included_at_restental_andreas_joystick_rumble_RumbleControl
#define _Included_at_restental_andreas_joystick_rumble_RumbleControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_restental_andreas_joystick_rumble_RumbleControl
 * Method:    setuprumble
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_restental_andreas_joystick_rumble_RumbleControl_setuprumble
  (JNIEnv *, jobject);

/*
 * Class:     at_restental_andreas_joystick_rumble_RumbleControl
 * Method:    startrumble
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_restental_andreas_joystick_rumble_RumbleControl_startrumble
  (JNIEnv *, jobject);

/*
 * Class:     at_restental_andreas_joystick_rumble_RumbleControl
 * Method:    stoprumble
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_restental_andreas_joystick_rumble_RumbleControl_stoprumble
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
