/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_restental_andreas_joystick_rumble_RumbleControl */

#ifndef _Included_at_restental_andreas_joystick_rumble_RumbleControl
#define _Included_at_restental_andreas_joystick_rumble_RumbleControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_restental_andreas_joystick_rumble_RumbleControl
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_restental_andreas_joystick_rumble_RumbleControl_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
